name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
         cd ${{ github.workspace }}/container
         docker build .  --tag acrpizzadefaulteastusnp76.azurecr.io/myapp:0.0.1
    
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        inlineScript: |
                    az login --service-principal -u f15382ba-78f5-4c43-90ef-7a9a0c8280bc -p IPz8Q~ULCALJJV0xd_JYw5Iue9hLSa4V~jBagbme -t f41f4204-5be7-4e45-8e45-cf5fcd55b425
                    az acr login -n acrpizzadefaulteastusnp76 --expose-token
                   

    - name: Container ACR
      run: |
           docker login acrpizzadefaulteastusnp76.azurecr.io -u acrpizzadefaulteastusnp76 -p CqtbrsbElwTAkqZZLZZogLUoYzgpiS2CAvX5vRsoZe+ACRDqFS1z
           docker push acrpizzadefaulteastusnp76.azurecr.io/myapp:0.0.1
